/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/index" |
       "/pages/authorizePage/index" |
       "/pages/home/SearchOverlay" |
       "/pages/mine/index" |
       "/pages/rank/index" |
       "/pages/teamPerson/index" |
       "/pageHome/details/index" |
       "/pageHome/payment/index" |
       "/pageHome/applySuccess/index" |
       "/pageHome/maintaincar/index" |
       "/pageHome/maintaincarLog/index" |
       "/pageRank/addressManage/index" |
       "/pageRank/addAddress/index" |
       "/pageRank/addressSuccess/index" |
       "/pageRank/incomeTeamDetails/index" |
       "/pageRank/pointsDetails/index" |
       "/pageRank/pointsRedemption/index" |
       "/pageMine/orderList/index" |
       "/pageMine/orderRefund/index" |
       "/pageMine/bankCardManage/index" |
       "/pageMine/addBankCard/index" |
       "/pageMine/myWallet/index" |
       "/pageMine/myPoints/index" |
       "/pageMine/taking/index" |
       "/pageMine/extractSuccess/index" |
       "/pageMine/authManage/index" |
       "/pageMine/companyAuth/index" |
       "/pageMine/personalAuth/index" |
       "/pageMine/myTeam/index" |
       "/pageMine/myteamAdd/index" |
       "/pageMine/setupPage/index" |
       "/pageMine/myAccount/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/rank/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
