/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/index" |
       "/pages/authorizePage/index" |
       "/pages/home/SearchOverlay" |
       "/pages/mine/index" |
       "/pages/rank/index" |
       "/pages/teamPerson/index" |
       "/pages/wisdom/index" |
       "/pageHome/details/index" |
       "/pageHome/detailshare/index" |
       "/pageHome/collectInfo/index" |
       "/pageHome/applyTraffic/index" |
       "/pageHome/applySuccess/index" |
       "/pageHome/productRank/index" |
       "/pageHome/welfare/index" |
       "/pageHome/traffic/index" |
       "/pageHome/sampleList/index" |
       "/pageHome/sampleDetails/index" |
       "/pageHome/storeDetails/index" |
       "/pageHome/maintaincar/index" |
       "/pageHome/maintaincarLog/index" |
       "/pageAi/findproducts/index" |
       "/pageAi/findLog/index" |
       "/pageAi/seekRecord/index" |
       "/pageAi/selectedCar/index" |
       "/pageAi/matchingDetails/index" |
       "/pageRank/searchExperts/index" |
       "/pageRank/addressManage/index" |
       "/pageRank/addAddress/index" |
       "/pageRank/addressSuccess/index" |
       "/pageRank/expertDetails/index" |
       "/pageRank/expertManage/index" |
       "/pageRank/incomeRecord/index" |
       "/pageRank/incomeTeamDetails/index" |
       "/pageRank/incomeUserDetails/index" |
       "/pageMine/bankCardManage/index" |
       "/pageMine/addBankCard/index" |
       "/pageMine/myWallet/index" |
       "/pageMine/taking/index" |
       "/pageMine/extractSuccess/index" |
       "/pageMine/authManage/index" |
       "/pageMine/companyAuth/index" |
       "/pageMine/personalAuth/index" |
       "/pageMine/myData/index" |
       "/pageMine/myTeam/index" |
       "/pageMine/myteamAdd/index" |
       "/pageMine/rulePage/index" |
       "/pageMine/setupPage/index" |
       "/pageMine/trafficleList/index" |
       "/pageMine/myAccount/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/wisdom/index" | "/pages/rank/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
